---
- name: configure firewall
  hosts: all
  tasks:
    - name: include variable file
      include_vars: lab-vars/allvars.yml

    - name: include the tasks
      include: lab-tasks/firewall.yml

- name: configure lamp servers
  hosts: lamp
  tasks:
    - name: include the variable file
      include_vars: lab-vars/allvars.yml

    - name: include the tasks
      include: lab-tasks/lamp.yml

- name: configure file servers
  hosts: file
  tasks:
    - name: include the variabe file
      include_vars: lab-vars/allvars.yml

    - name: include the tasks
      include: lab-tasks/file.yml


